ALTER TYPE "ExamProctorEventType" ADD VALUE IF NOT EXISTS 'HEAD_TURN_HORIZONTAL';
ALTER TYPE "ExamProctorEventType" ADD VALUE IF NOT EXISTS 'EYE_MOVEMENT_HORIZONTAL';
ALTER TYPE "ExamProctorEventType" ADD VALUE IF NOT EXISTS 'PHONE_DETECTED';
